export const INPUT_CHANGE = "INPUT_CHANGE";
export const SUBMIT = "SUBMIT";
export const LOGIN = "LOGIN";
export const RESET = "RESET";
export const GET_ERRORS="GET_ERRORS";
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const UPLOAD_DCOUMENT_SUCCESS="UPLOAD_DCOUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAIL="UPLOAD_DOCUMENT_FAIL";